Repository kisanola/tech-community-frontend, pull requests merged in 2019-10, with the labels that each got.

#8 Like feature implementation
  src/Api/server.js
  src/__tests__/components/Like.test.js
  src/__tests__/components/__snapshots__/Like.test.js.snap
  src/__tests__/components/__snapshots__/PostTextArea.test.js.snap
  src/__tests__/components/feed.test.js
  src/actions/likeActions.js
  src/components/Feed/Feed.jsx
  src/components/Feed/Feed.scss
  src/components/Like/Like.jsx
  src/components/Like/Like.scss
  src/components/Login/socialAuth.scss
  src/components/PostTextArea/PostTextArea.scss
  src/pages/Home/Home.jsx
Labels: REVIEWING

#9 Share Post implementation
  package.json
  src/__tests__/actions/sharePost.test.js
  src/__tests__/components/SharePost.test.js
  src/__tests__/components/__snapshots__/SharePost.test.js.snap
  src/__tests__/components/__snapshots__/feed.test.js.snap
  src/__tests__/reducer/sharePost.test.js
  src/actionTypes/sharePostTypes.js
  src/actions/postActions.js
  src/actions/sharePostAction.js
  src/assets/images/facebook_logo.png
  src/assets/images/twitter_logo.png
  src/components/Feed/Feed.jsx
  src/components/SharePost/SharePost.jsx
  src/components/SharePost/SharePost.scss
  src/constants/index.js
  src/reducers/index.js
  src/reducers/sharePost.js
Labels: enhancement

#28 add related posts on single post page
  .eslintrc.json
  src/__tests__/components/SinglePost.test.js
  src/actionTypes/singlePostTypes.js
  src/actions/fetchSinglePostAction.js
  src/components/PostComponent/PostCard.scss
  src/components/SinglePost/SinglePost.jsx
  src/components/SinglePost/SinglePost.scss
  src/pages/SinglePost/SinglePost.jsx
  src/reducers/singlePost.js
  src/store/initialState.js
Labels: REVIEW ME

#29 Add the NotFound component
  src/assets/images/girl.svg
  src/assets/images/man.jpg
  src/assets/images/notFound.png
  src/components/Feed/Feed.jsx
  src/components/NotFound/NotFound.jsx
  src/components/NotFound/NotFound.scss
Labels: REVIEW ME
